name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
      run: heroku container:login
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
      run: heroku container:push -a docker-nestjs-api web 
    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
      run: heroku container:release -a docker-nestjs-api web 

